export type Discover = {
    discoverList: any[] | null,
    setDiscoverList: React.Dispatch<any>,
    movieList: any[] | null,
    setMovieList: React.Dispatch<any>,
    userMovieList: any[] | null,
    setUserMovieList: React.Dispatch<any>,
    discoverTitle: string | null,
    setDiscoverTitle: (title: string) => void,
    movieisFun: string | null,
    setMovieIsFun: (movieisFun: string) => void,
    impressionMovie: string | null,
    setImpressionMovie: (impressionMovie: string) => void,
    movieIsRecom: string | null,
    setMovieIsRecom: (movieIsRecom: string) => void,
    id: number,
    title: string,
}